# Generated by Django 3.1.7 on 2021-04-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210330_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='friend',
        ),
    ]
